# Levels
ricebeach_1_exit_1      = "Rice Beach 01 - Normal Exit"
ricebeach_2_exit_1      = "Rice Beach 02 - Normal Exit"
ricebeach_3_exit_1      = "Rice Beach 03 - Normal Exit"
ricebeach_3_exit_2      = "Rice Beach 03 - Secret Exit"
ricebeach_4_exit_1      = "Rice Beach 04 - Normal Exit"
ricebeach_5_exit_1      = "Rice Beach 05 - Normal Exit"
ricebeach_6_exit_1      = "Rice Beach 06 - Normal Exit"
ricebeach_boss          = "Rice Beach - Spiked Koopa Boss"

mtteapot_7_exit_1       = "Mt. Teapot 07 - Normal Exit"
mtteapot_8_exit_1       = "Mt. Teapot 08 - Normal Exit"
mtteapot_8_exit_2       = "Mt. Teapot 08 - Secret Exit"
mtteapot_9_exit_1       = "Mt. Teapot 09 - Normal Exit"
mtteapot_10_exit_1      = "Mt. Teapot 10 - Normal Exit"
mtteapot_11_exit_1      = "Mt. Teapot 11 - Normal Exit"
mtteapot_12_exit_1      = "Mt. Teapot 12 - Normal Exit"
mtteapot_13_exit_1      = "Mt. Teapot 13 - Normal Exit"
mtteapot_boss           = "Mt. Teapot - Minotaur Boss"

sherbetland_14_exit_1   = "Sherbet Land 14 - Normal Exit"
sherbetland_15_exit_1   = "Sherbet Land 15 - Normal Exit"
sherbetland_15_exit_2   = "Sherbet Land 15 - Secret Exit"
sherbetland_16_exit_1   = "Sherbet Land 16 - Normal Exit"
sherbetland_16_exit_2   = "Sherbet Land 16 - Secret Exit"
sherbetland_17_exit_1   = "Sherbet Land 17 - Normal Exit"
sherbetland_18_exit_1   = "Sherbet Land 18 - Normal Exit"
sherbetland_19_exit_1   = "Sherbet Land 19 - Normal Exit"
sherbetland_boss        = "Sherbet Land - Penguin Boss"

stovecanyon_20_exit_1   = "Stove Canyon 20 - Normal Exit"
stovecanyon_21_exit_1   = "Stove Canyon 21 - Normal Exit"
stovecanyon_22_exit_1   = "Stove Canyon 22 - Normal Exit"
stovecanyon_23_exit_1   = "Stove Canyon 23 - Normal Exit"
stovecanyon_23_exit_2   = "Stove Canyon 23 - Secret Exit"
stovecanyon_24_exit_1   = "Stove Canyon 24 - Normal Exit"
stovecanyon_25_exit_1   = "Stove Canyon 25 - Normal Exit"
stovecanyon_boss        = "Stove Canyon - Devil's Head Boss"

ssteacup_26_exit_1      = "SS Tea Cup 26 - Normal Exit"
ssteacup_27_exit_1      = "SS Tea Cup 27 - Normal Exit"
ssteacup_28_exit_1      = "SS Tea Cup 28 - Normal Exit"
ssteacup_29_exit_1      = "SS Tea Cup 29 - Normal Exit"
ssteacup_30_exit_1      = "SS Tea Cup 30 - Normal Exit"
ssteacup_boss           = "SS Tea Cup - Bobo Boss"

parsleywoods_31_exit_1  = "Parsley Woods 31 - Normal Exit"
parsleywoods_32_exit_1  = "Parsley Woods 32 - Normal Exit"
parsleywoods_33_exit_1  = "Parsley Woods 33 - Normal Exit"
parsleywoods_34_exit_1  = "Parsley Woods 34 - Normal Exit"
parsleywoods_35_exit_1  = "Parsley Woods 35 - Normal Exit"
parsleywoods_36_exit_1  = "Parsley Woods 36 - Normal Exit"
parsleywoods_boss       = "Parsley Woods - Ghost Boss"

syrupcastle_37_exit_1   = "Syrup Castle 37 - Normal Exit"
syrupcastle_38_exit_1   = "Syrup Castle 38 - Normal Exit"
syrupcastle_39_exit_1   = "Syrup Castle 39 - Normal Exit"
syrupcastle_40_exit_1   = "Syrup Castle 40 - Normal Exit"
syrupcastle_boss        = "Syrup Castle - Genie Boss"

#Treasures
ricebeach_3_treasure    = "Rice Beach 03 - Treasure A"
mtteapot_9_treasure     = "Mt. Teapot 09 - Treasure B"
mtteapot_11_treasure    = "Mt. Teapot 11 - Treasure C"
sherbetland_16_treasure = "Sherbet Land 16 - Treasure D"
sherbetland_17_treasure = "Sherbet Land 17 - Treasure E"
sherbetland_18_treasure = "Sherbet Land 18 - Treasure F"
stovecanyon_20_treasure = "Stove Canyon 20 - Treasure G"
stovecanyon_24_treasure = "Stove Canyon 24 - Treasure H"
ssteacup_26_treasure    = "SS Tea Cup 26 - Treasure I"
ssteacup_29_treasure    = "SS Tea Cup 29 - Treasure J"
ssteacup_30_treasure    = "SS Tea Cup 30 - Treasure K"
parsleywoods_31_treasure= "Parsley Woods 31 - Treasure L"
parsleywoods_34_treasure= "Parsley Woods 34 - Treasure M"
syrupcastle_37_treasure = "Syrup Castle 37 - Treasure N"
syrupcastle_39_treasure = "Syrup Castle 39 - Treasure O"

#Regions
menu_region             = "Menu"
overworld_region        = "Overworld"
overworld_tile          = "Overworld - Tile"
garlic_goal             = "Garlic Hunt Goal"

ricebeach_region        = "Rice Beach"
mtteapot_region         = "Mt. Teapot"
sherbetland_region      = "Sherbet Land"
stovecanyon_region      = "Stove Canyon"
ssteacup_region         = "SS Teacup"
parsleywoods_region     = "Parsley Woods"
syrupcastle_region      = "Syrup Castle"

genie_region            = "Genie - Region"
genie                   = "Genie"

ricebeach_1_region      = "Rice Beach 01"
ricebeach_2_region      = "Rice Beach 02"
ricebeach_3_region      = "Rice Beach 03"
ricebeach_4_region      = "Rice Beach 04"
ricebeach_5_region      = "Rice Beach 05"
ricebeach_6_region      = "Rice Beach 06"

mtteapot_7_region       = "Mt. Teapot 07"
mtteapot_8_region       = "Mt. Teapot 08"
mtteapot_9_region       = "Mt. Teapot 09"
mtteapot_10_region      = "Mt. Teapot 10"
mtteapot_11_region      = "Mt. Teapot 11"
mtteapot_12_region      = "Mt. Teapot 12"
mtteapot_13_region      = "Mt. Teapot 13"

sherbetland_14_region   = "Sherbet Land 14"
sherbetland_15_region   = "Sherbet Land 15"
sherbetland_16_region   = "Sherbet Land 16"
sherbetland_17_region   = "Sherbet Land 17"
sherbetland_18_region   = "Sherbet Land 18"
sherbetland_19_region   = "Sherbet Land 19"

stovecanyon_20_region   = "Stove Canyon 20"
stovecanyon_21_region   = "Stove Canyon 21"
stovecanyon_22_region   = "Stove Canyon 22"
stovecanyon_23_region   = "Stove Canyon 23"
stovecanyon_24_region   = "Stove Canyon 24"
stovecanyon_25_region   = "Stove Canyon 25"

ssteacup_26_region      = "SS Tea Cup 26"
ssteacup_27_region      = "SS Tea Cup 27"
ssteacup_28_region      = "SS Tea Cup 28"
ssteacup_29_region      = "SS Tea Cup 29"
ssteacup_30_region      = "SS Tea Cup 30"

parsleywoods_31_region  = "Parsley Woods 31"
parsleywoods_32_region  = "Parsley Woods 32"
parsleywoods_33_region  = "Parsley Woods 33"
parsleywoods_34_region  = "Parsley Woods 34"
parsleywoods_35_region  = "Parsley Woods 35"
parsleywoods_36_region  = "Parsley Woods 36"

syrupcastle_37_region   = "Syrup Castle 37"
syrupcastle_38_region   = "Syrup Castle 38"
syrupcastle_39_region   = "Syrup Castle 39"
syrupcastle_40_region   = "Syrup Castle 40"

ricebeach_1_tile     = "Rice Beach 01 - Tile"
ricebeach_2_tile     = "Rice Beach 02 - Tile"
ricebeach_3_tile     = "Rice Beach 03 - Tile"
ricebeach_4_tile     = "Rice Beach 04 - Tile"
ricebeach_5_tile     = "Rice Beach 05 - Tile"
ricebeach_6_tile     = "Rice Beach 06 - Tile"

mtteapot_7_tile      = "Mt. Teapot 07 - Tile"
mtteapot_8_tile      = "Mt. Teapot 08 - Tile"
mtteapot_9_tile      = "Mt. Teapot 09 - Tile"
mtteapot_10_tile     = "Mt. Teapot 10 - Tile"
mtteapot_11_tile     = "Mt. Teapot 11 - Tile"
mtteapot_12_tile     = "Mt. Teapot 12 - Tile"
mtteapot_13_tile     = "Mt. Teapot 13 - Tile"

sherbetland_14_tile  = "Sherbet Land 14 - Tile"
sherbetland_15_tile  = "Sherbet Land 15 - Tile"
sherbetland_16_tile  = "Sherbet Land 16 - Tile"
sherbetland_17_tile  = "Sherbet Land 17 - Tile"
sherbetland_18_tile  = "Sherbet Land 18 - Tile"
sherbetland_19_tile  = "Sherbet Land 19 - Tile"

stovecanyon_20_tile  = "Stove Canyon 20 - Tile"
stovecanyon_21_tile  = "Stove Canyon 21 - Tile"
stovecanyon_22_tile  = "Stove Canyon 22 - Tile"
stovecanyon_23_tile  = "Stove Canyon 23 - Tile"
stovecanyon_24_tile  = "Stove Canyon 24 - Tile"
stovecanyon_25_tile  = "Stove Canyon 25 - Tile"

ssteacup_26_tile     = "SS Tea Cup 26 - Tile"
ssteacup_27_tile     = "SS Tea Cup 27 - Tile"
ssteacup_28_tile     = "SS Tea Cup 28 - Tile"
ssteacup_29_tile     = "SS Tea Cup 29 - Tile"
ssteacup_30_tile     = "SS Tea Cup 30 - Tile"

parsleywoods_31_tile = "Parsley Woods 31 - Tile"
parsleywoods_32_tile = "Parsley Woods 32 - Tile"
parsleywoods_33_tile = "Parsley Woods 33 - Tile"
parsleywoods_34_tile = "Parsley Woods 34 - Tile"
parsleywoods_35_tile = "Parsley Woods 35 - Tile"
parsleywoods_36_tile = "Parsley Woods 36 - Tile"

syrupcastle_37_tile  = "Syrup Castle 37 - Tile"
syrupcastle_38_tile  = "Syrup Castle 38 - Tile"
syrupcastle_39_tile  = "Syrup Castle 39 - Tile"
syrupcastle_40_tile  = "Syrup Castle 40 - Tile"